const audioList = [
  { name: "dostoyevsky", file: "audio/dostoyevsky.wav" },
  { name: "mikhailovsky", file: "audio/mikhailovsky.wav" },
  { name: "rostropovich", file: "audio/rostropovich.wav" },
  { name: "di benedetto", file: "audio/di%20benedetto.wav" },
  { name: "bartholomeo", file: "audio/bartholomeo.wav" },
  { name: "rinaldi-catalano", file: "audio/rinaldi-catalano.wav" },
  { name: "de albuquerque", file: "audio/de%20albuquerque.wav" },
  { name: "monteiro de barros", file: "audio/monteiro%20de%20barros.wav" },
  { name: "fernandes-duarte", file: "audio/fernandes-duarte.wav" },
  { name: "fernández-lópez", file: "audio/fern%C3%A1ndez-l%C3%B3pez.wav" },
  { name: "gonzález-álvarez", file: "audio/gonz%C3%A1lez-%C3%A1lvarez.wav" },
  { name: "villanueva-rodríguez", file: "audio/villanueva-rodr%C3%ADguez.wav" },
  { name: "charpentier-dupont", file: "audio/charpentier-dupont.wav" },
  { name: "bourgeois-magnan", file: "audio/bourgeois-magnan.wav" },
  { name: "de la fontaine", file: "audio/de%20la%20fontaine.wav" },
  { name: "papadopoulos", file: "audio/papadopoulos.wav" },
  { name: "christodoulopoulos", file: "audio/christodoulopoulos.wav" },
  { name: "karagiannopoulos", file: "audio/karagiannopoulos.wav" },
  { name: "szabados-kovács", file: "audio/szabados-kov%C3%A1cs.wav" },
  { name: "lévai-hunyady", file: "audio/l%C3%A9vai-hunyady.wav" },
  { name: "guðmundsdóttir", file: "audio/gu%C3%B0mundsd%C3%B3ttir.wav" },
  { name: "jónsdóttir-larusson", file: "audio/j%C3%B3nsd%C3%B3ttir-larusson.wav" },
  { name: "shevchenko-petrov", file: "audio/shevchenko-petrov.wav" },
  { name: "yarmolenko-vysotsky", file: "audio/yarmolenko-vysotsky.wav" }
];